#cloud-config 
users:
  - name: nutanix
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: wheel
    shell: /bin/bash
chpasswd:
  list: |
    nutanix:nutanix/4u
  expire: False
ssh_pwauth: true
packages:
  - git